<script src="/js/jquery.js"></script><!--jquery script-->
<script src="/js/jquery-migrate.js"></script><!--jquery script-->
<script src="/js/bootstrap.js"></script>
<script src="/js/imagesloaded.js"></script>
<script src="/js/isotope.js"></script>
<script src="/js/flexslider.js"></script>
<script src="/js/scriptcontact.js"></script>
<script src="/js/scriptsubmit.js"></script>
<script src="/js/magnific_popup.js"></script>
<script src="/js/jquery.sequence.js"></script>
<script src="/js/jquery.bxslider.js"></script>
<script src="/js/camera.js"></script>
<script src="/js/jquery.ba-hashchange.min.js"></script>
<script src="/js/jquery.ui.widget.js"></script>
<script src="/js/jquery.easing.js"></script>
<script src="/js/twitter.js"></script>
<script src="/js/scripts.js"></script>
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.js"></script>